version: "3.7"
services:

  mysql-wp-${SITE}:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mysql-vol-1:/var/lib/mysql
    networks:
      wp-${SITE}-network:
        aliases:
          - mysql

  nginx-wp-${SITE}:
    image: ${SITE}/nginx-wp:1.15.11
    build: data/Docker/nginx
    restart: always
    volumes:
      - ./data/conf/nginx:/etc/nginx
      - /var/www/${SITE_LONG}:/var/www
    depends_on:
      - mysql-wp-${SITE}
      - php-fpm-wp-${SITE}
      - redis-wp-${SITE}
    networks:
      wp-${SITE}-network:
        aliases:
          - nginx
      proxy-network:

  php-fpm-wp-${SITE}:
    image: ${SITE}/php-fpm-wp:7.3.4
    build: data/Docker/php-fpm
    restart: always
    volumes:
      - /var/www/${SITE_LONG}:/var/www
      - ./data/conf/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      wp-${SITE}-network:
        aliases:
          - php-fpm

  redis-wp-${SITE}:
    image: redis:alpine
    restart: always
    networks:
      wp-${SITE}-network:
        aliases:
          - redis

networks:
  wp-${SITE}-network:
    name: wp-${SITE}-network
  proxy-network:
    external: true

volumes:
  mysql-vol-1:
