version: "3.7"
services:

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mysql-vol-1:/var/lib/mysql
    networks:
      wp-network:
        aliases:
          - mysql

  nginx-wp:
    image: wordpress-docker/nginx-wp
    build: data/Docker/nginx
    restart: always
    volumes:
      - ./data/conf/nginx:/etc/nginx
      - ${WWW_ROOT}:/var/www
    depends_on:
      - mysql
      - php-fpm-wp
      - redis
    networks:
      wp-network:
        aliases:
          - nginx
      proxy-network:

  php-fpm-wp:
    image: hermsi/alpine-fpm-php
    restart: always
    volumes:
      - ${WWW_ROOT}:/var/www
      - ./data/conf/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      wp-network:
        aliases:
          - php-fpm

  redis:
    image: redis:alpine
    restart: always
    networks:
      wp-network:
        aliases:
          - redis

networks:
  wp-network:
  proxy-network:
    external: true

volumes:
  mysql-vol-1:
