version: "3.7"
services:

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mysql-vol-1:/var/lib/mysql
    networks:
      wp-network:

  nginx-wp:
    image: wordpress-docker/nginx-wp
    build: data/docker/nginx
    restart: always
    volumes:
      - ./data/srv:/var/www
      - ./data/conf/nginx:/etc/nginx
    depends_on:
      - mysql
      - php-fpm-wp
      - redis
    networks:
      wp-network:
        aliases:
          - nginx
      proxy-network:
        aliases:
          - nginx-wp-musikfest

  php-fpm-wp:
    image: wordpress-docker/php-fpm-wp
    build:
      context: data/docker/php-fpm
      args:
        - PHP_VERSION=7.3.4
        - PHPREDIS_VERSION=4.3.0
    restart: always
    volumes:
      - ./data/srv:/var/www
      - ./data/conf/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    user: root:root
    networks:
      wp-network:
        aliases:
          - php-fpm

  redis:
    image: redis
    restart: always
    volumes:
      - redis-vol-1:/data
    networks:
      wp-network:

networks:
  wp-network:
  proxy-network:
    external: true

volumes:
  mysql-vol-1:
  redis-vol-1: